[project]
name = "voice-to-voice-agentic-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=1.3.5",
    "pandas>=2.3.3",
    "sentence-transformers>=5.1.2",
    "tqdm>=4.67.1",
]
